### ISSUE TITLE
Problema cuando hay una línea en blanco en CourseList.txt

### ISSUE THREAD

**Issue by Cristinasj** [RhinoBlindado/pradoscraper#1]
El programa me dio el siguiente error 

4 / 4
Traceback (most recent call last):
  File "webPrado.py", line 221, in <module>
    main()
  File "webPrado.py", line 206, in main
    courseRead(courses, driver)
  File "webPrado.py", line 110, in courseRead
    actualCourse.click()
  File "/home/cristina/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/cristina/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/cristina/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/cristina/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: Element <h4> could not be scrolled into view

El problema es que me había dejado la última línea en blanco en CourseList.txt. El problema se solucionó cuando borré el último salto de línea. 

El programa podría comprobar de alguna forma si son líneas vacías para evitar que a otra persona le de este error.

**Comment by RhinoBlindado** [comment]
Entendido. Lo apuntaré para resolverlo, además de que estoy pensando en automatizar el relleno de asignaturas.

 _Posiblemente meterlo dentro de una base de datos también_
